NDS-79 Phase banner component
nice-digital/nice-design-system pull request #236
Opened 2021-10-27 11:23 UTC by wa-rren-dev

https://nicedigital.atlassian.net/browse/NDS-79

2021-11-01 16:00 UTC, ediblecode requested changes

2021-11-01 16:00 UTC, ediblecode commented on components/nds-phase-banner/README.md
> +@import "~@nice-digital/nds-alert/scss/alert";
This should be phase banner scss import

2021-11-01 16:00 UTC, ediblecode commented on components/nds-phase-banner/README.md
> +<div class="alert alert--info">
Same as CSS comment above - wrong markup snippet

2021-11-01 16:00 UTC, ediblecode commented on components/nds-phase-banner/README.md
> +#### Props
Is it worth also saying that any other props are spread over the wrapping element?

2021-11-01 16:00 UTC, ediblecode commented on components/nds-phase-banner/README.md
> +#### Props
I think we do this elsewhere in readmes

2021-11-01 16:00 UTC, ediblecode commented on components/nds-phase-banner/__tests__/nds-phase-banner.test.js
> +	});
Can we add a test for spreading additional props over the wrapping element?

2021-11-01 16:56 UTC, wa-rren-dev commented on components/nds-phase-banner/README.md
> +<div class="alert alert--info">
🤦

2021-11-02 11:08 UTC, ediblecode approved these changes

2021-11-02 11:08 UTC, merged